"""
AutoDock Vina Pose Extractor & Data Logger
------------------------------------------
A lightweight Python utility designed to parse multi-model .pdbqt files 
generated by AutoDock Vina. It automatically splits structural poses into 
standalone, universally compatible .pdb files while extracting thermodynamic 
binding affinities and logging them to a centralized validation CSV.

Requires: Python 3.6+
"""
import argparse
import csv
import re
import sys
from pathlib import Path


def split_poses_and_extract_data(pdbqt_path, output_dir):
    """
    Parses a multi-model PDBQT file from AutoDock Vina, extracts individual 
    poses into clean PDB files, captures the binding affinity scores, 
    and outputs a centralized data summary table.
    
    Args:
        pdbqt_path (str or Path): Path to input PDBQT file
        output_dir (str or Path): Directory for output PDB files and CSV
        
    Raises:
        FileNotFoundError: If PDBQT file does not exist
        IOError: If unable to read or write files
    """
    pdbqt_path = Path(pdbqt_path)
    output_dir = Path(output_dir)
    
    # Validation
    if not pdbqt_path.exists():
        raise FileNotFoundError(f"PDBQT file not found: {pdbqt_path}")
    
    if not pdbqt_path.is_file():
        raise ValueError(f"Input path is not a file: {pdbqt_path}")
    
    output_dir.mkdir(parents=True, exist_ok=True)

    # Read PDBQT file
    try:
        with open(pdbqt_path, 'r') as file:
            content = file.read()
    except IOError as e:
        raise IOError(f"Failed to read PDBQT file: {e}")

    chunks = content.split('MODEL')
    base_name = pdbqt_path.stem
    
    data_log = []
    count = 1

    for chunk in chunks:
        if not chunk.strip():
            continue
            
        if 'ATOM' in chunk or 'HETATM' in chunk:
            pose_lines = chunk.strip().splitlines()
            
            # Extract binding affinity score
            energy_score = "0.0"
            for line in pose_lines:
                if "REMARK VINA RESULT" in line:
                    match = re.search(r'REMARK VINA RESULT:\s*([-+]?\d+\.?\d*)', line)
                    if match:
                        energy_score = match.group(1)
                    break
            
            # Filter ATOM/HETATM lines
            pdb_lines = [line for line in pose_lines if line.startswith(('ATOM', 'HETATM'))]
            pdb_lines.append('END')

            # Write PDB file with proper context manager
            filename = f"{base_name}_pose_{count}_{energy_score}kcal.pdb"
            out_path = output_dir / filename
            
            try:
                with open(out_path, 'w') as out_file:
                    out_file.write('\n'.join(pdb_lines))
            except IOError as e:
                print(f"[WARNING] Failed to write {filename}: {e}")
                continue
            
            data_log.append({
                'Pose_Number': count,
                'Filename': filename,
                'Binding_Affinity_kcal_mol': float(energy_score)
            })
            
            count += 1

    # Write CSV summary
    csv_filename = f"{base_name}_docking_summary.csv"
    csv_path = output_dir / csv_filename
    
    try:
        with open(csv_path, 'w', newline='') as csv_file:
            fieldnames = ['Pose_Number', 'Filename', 'Binding_Affinity_kcal_mol']
            writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(data_log)
    except IOError as e:
        raise IOError(f"Failed to write CSV: {e}")

    # Print success summary
    print("\n[SUCCESS] Pipeline Execution Complete.")
    print(f"-> Extracted {count - 1} individual poses into: '{output_dir}'")
    print(f"-> Automated data validation sheet generated: '{csv_path}'\n")


def main():
    """Command-line interface for pose extraction."""
    parser = argparse.ArgumentParser(
        description="Extract individual poses from AutoDock Vina PDBQT output files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python split_poses_2.py redock-talo-10.pdbqt
  python split_poses_2.py redock-talo-10.pdbqt -o ./my_output
  python split_poses_2.py /path/to/file.pdbqt -o extracted_poses
        """
    )
    
    parser.add_argument(
        "pdbqt_file",
        help="Path to input PDBQT file from AutoDock Vina"
    )
    parser.add_argument(
        "-o", "--output",
        default="extracted_poses",
        help="Output directory for PDB files and CSV (default: extracted_poses)"
    )
    
    args = parser.parse_args()
    
    try:
        split_poses_and_extract_data(args.pdbqt_file, args.output)
    except (FileNotFoundError, IOError, ValueError) as e:
        print(f"\n[ERROR] {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
