"""
AutoDock Vina Pose Extractor & Data Logger
------------------------------------------
A lightweight Python utility designed to parse multi-model .pdbqt files 
generated by AutoDock Vina. It automatically splits structural poses into 
standalone, universally compatible .pdb files while extracting thermodynamic 
binding affinities and logging them to a centralized validation CSV.

Designed for high data integrity and dual-compatibility (Python 2 & 3).
"""
import os
import re
import csv
import sys

def split_poses_and_extract_data(pdbqt_path, output_dir):
    """
    Parses a multi-model PDBQT file from AutoDock Vina, extracts individual 
    poses into clean PDB files, captures the binding affinity scores, 
    and outputs a centralized data summary table.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    with open(pdbqt_path, 'r') as file:
        content = file.read()

    chunks = content.split('MODEL')
    base_name = os.path.splitext(os.path.basename(pdbqt_path))[0]
    
    data_log = []
    count = 1

    for chunk in chunks:
        if not chunk.strip():
            continue
            
        if 'ATOM' in chunk or 'HETATM' in chunk:
            pose_lines = chunk.strip().splitlines()
            
            energy_score = "0.0"
            for line in pose_lines:
                if "REMARK VINA RESULT" in line:
                    match = re.search(r'REMARK VINA RESULT:\s*([-\d.]+)', line)
                    if match:
                        energy_score = match.group(1)
                    break
            
            pdb_lines = [line for line in pose_lines if line.startswith(('ATOM', 'HETATM'))]
            pdb_lines.append('END')

            filename = "{}_pose_{}_{}kcal.pdb".format(base_name, count, energy_score)
            out_path = os.path.join(output_dir, filename)
            
            with open(out_path, 'w') as out_file:
                out_file.write('\n'.join(pdb_lines))
            
            data_log.append({
                'Pose_Number': count,
                'Filename': filename,
                'Binding_Affinity_kcal_mol': float(energy_score)
            })
            
            count += 1

    csv_filename = "{}_docking_summary.csv".format(base_name)
    csv_path = os.path.join(output_dir, csv_filename)
    
    # VERSION CHECK: Python 2 vs Python 3 CSV handling
    if sys.version_info[0] < 3:
        csv_file = open(csv_path, 'wb') # Python 2 requires binary mode
    else:
        csv_file = open(csv_path, 'w', newline='') # Python 3 requires newline argument
        
    try:
        fieldnames = ['Pose_Number', 'Filename', 'Binding_Affinity_kcal_mol']
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        
        writer.writeheader()
        writer.writerows(data_log)
    finally:
        csv_file.close()

    print("\n[SUCCESS] Pipeline Execution Complete.")
    print("-> Extracted {} individual poses into: '{}'".format(count - 1, output_dir))
    print("-> Automated data validation sheet generated: '{}'\n".format(csv_path))


# --- PRODUCTION RUN CONFIGURATION ---
if __name__ == "__main__":
    # Point this to your real file path
    raw_docking_output = r"sample_docking_output.pdbqt"
    
    # Saving straight to your Downloads folder to guarantee access permissions
    target_destination = r"extracted_poses"
    
    split_poses_and_extract_data(raw_docking_output, target_destination)